const translations = {
  ua: {"nav.about":"Про нас","nav.services":"Послуги","nav.doctors":"Лікарі","nav.contacts":"Контакти","hero.eyebrow":"Сімейна стоматологія нового покоління","hero.title":"Ваша усмішка. Наша турбота.","hero.text":"Безболісне лікування та уважний підхід до кожного члена родини. Первинна консультація безкоштовно.","hero.cta":"Записатися на консультацію ↗","hero.more":"Дізнатися більше ↓","hero.proof":"років створюємо здорові усмішки","hero.noteTitle":"Піклуємося по-справжньому","hero.noteText":"Спокійно. Професійно. Поруч.","hero.badge":"пацієнтів рекомендують нас","about.eyebrow":"Про Milo Dental","about.title":"Стоматологія, в якій легко бути собою.","about.text":"Ми поєднали сучасні технології, доказову медицину та людяне ставлення. Тут не страшно, зрозуміло і завжди є час на ваші запитання.","about.link":"Познайомитися з нами ↗","about.stat1":"Діагностика<br>без поспіху","about.stat2":"Прозорий<br>план лікування","about.stat3":"Комфорт<br>на кожному кроці","services.eyebrow":"Що ми робимо","services.title":"Послуги для усмішок<br><em>будь-якого віку.</em>","services.text":"Від профілактики до складних рішень. Обираємо лише те, що справді потрібно саме вам.","services.implants":"Імплантація","services.veneers":"Вініри","services.braces":"Брекети та елайнери","services.whitening":"Відбілювання зубів","services.placeholder":"Детальний опис послуги з'явиться тут","doctors.eyebrow":"Команда Milo","doctors.title":"Люди, яким<br><em>можна довіряти.</em>","doctors.link":"Обрати свого лікаря ↗","doctors.anna":"Анна Коваль","doctors.annaRole":"Стоматолог-терапевт","doctors.annaExp":"12 років досвіду","doctors.max":"Максим Левченко","doctors.maxRole":"Хірург-імплантолог","doctors.maxExp":"15 років досвіду","doctors.book":"Записатися до Анни ↗","doctors.bookMax":"Записатися до Максима ↗","contact.eyebrow":"Перший крок до здорової усмішки","contact.title":"Давайте<br><em>познайомимося.</em>","contact.text":"Залиште контакти, і адміністратор зв'яжеться з вами, щоб підібрати зручний час.","contact.address":"вул. Велика Васильківська, 72, Київ","contact.hours":"Пн - Пт: 08:00 - 20:00<br>Сб: 09:00 - 16:00","form.name":"Ваше ім'я","form.phone":"Номер телефону","form.message":"Коротко про проблему або мету візиту","form.namePlaceholder":"Олена","form.messagePlaceholder":"Розкажіть, чим ми можемо допомогти","form.submit":"Відправити заявку ↗","floating":"Записатися","modal.eyebrow":"Безкоштовна консультація","modal.title":"Заплануємо<br><em>ваш візит.</em>","modal.text":"Залиште номер, і ми передзвонимо протягом робочого дня.","modal.submit":"Чекаю на дзвінок ↗","footer.copy":"З турботою про усмішки<br>вашої родини.","footer.rights":"Всі права захищено","footer.up":"На початок ↑"},
  en: {"nav.about":"About us","nav.services":"Services","nav.doctors":"Doctors","nav.contacts":"Contacts","hero.eyebrow":"A new generation family dental clinic","hero.title":"Your smile. Our care.","hero.text":"Pain-free treatment and a thoughtful approach for every member of your family. Your first consultation is free.","hero.cta":"Book a free consultation ↗","hero.more":"Discover more ↓","hero.proof":"years creating healthy smiles","hero.noteTitle":"Care that feels real","hero.noteText":"Calm. Professional. Close.","hero.badge":"of patients recommend us","about.eyebrow":"About Milo Dental","about.title":"A dental clinic where you can be yourself.","about.text":"We combine modern technology, evidence-based medicine and a human touch. No pressure, clear answers and time for your questions.","about.link":"Meet our approach ↗","about.stat1":"Diagnosis<br>without rush","about.stat2":"A clear<br>treatment plan","about.stat3":"Comfort<br>at every step","services.eyebrow":"What we do","services.title":"Care for smiles<br><em>of every age.</em>","services.text":"From prevention to complex solutions. We recommend only what is truly right for you.","services.implants":"Implantology","services.veneers":"Veneers","services.braces":"Braces and aligners","services.whitening":"Teeth whitening","services.placeholder":"Detailed service description coming soon","doctors.eyebrow":"The Milo team","doctors.title":"People you<br><em>can trust.</em>","doctors.link":"Choose your doctor ↗","doctors.anna":"Anna Koval","doctors.annaRole":"General dentist","doctors.annaExp":"12 years of experience","doctors.max":"Maksym Levchenko","doctors.maxRole":"Implant surgeon","doctors.maxExp":"15 years of experience","doctors.book":"Book with Anna ↗","doctors.bookMax":"Book with Maksym ↗","contact.eyebrow":"The first step to a healthy smile","contact.title":"Let’s<br><em>get acquainted.</em>","contact.text":"Leave your details and our administrator will call to find the best time for you.","contact.address":"72 Velyka Vasylkivska St, Kyiv","contact.hours":"Mon - Fri: 08:00 - 20:00<br>Sat: 09:00 - 16:00","form.name":"Your name","form.phone":"Phone number","form.message":"A short note about your needs","form.namePlaceholder":"Olena","form.messagePlaceholder":"Tell us how we can help","form.submit":"Send request ↗","floating":"Book now","modal.eyebrow":"Free consultation","modal.title":"Let’s plan<br><em>your visit.</em>","modal.text":"Leave your number and we will call you back during business hours.","modal.submit":"Request a call ↗","footer.copy":"Caring for the smiles<br>of your family.","footer.rights":"All rights reserved","footer.up":"Back to top ↑"}
};

const header = document.querySelector('.site-header');
const menuToggle = document.querySelector('.menu-toggle');
const mobileNav = document.querySelector('.mobile-nav');
const modal = document.querySelector('#booking-modal');

function setLanguage(lang) {
  document.documentElement.lang = lang === 'ua' ? 'uk' : 'en';
  document.querySelectorAll('[data-i18n]').forEach((element) => {
    const value = translations[lang][element.dataset.i18n];
    if (value) element.innerHTML = value;
  });
  document.querySelectorAll('[data-i18n-placeholder]').forEach((element) => {
    const value = translations[lang][element.dataset.i18nPlaceholder];
    if (value) element.placeholder = value;
  });
  document.querySelectorAll('.language').forEach((button) => button.classList.toggle('is-active', button.dataset.lang === lang));
  localStorage.setItem('milo-language', lang);
}

document.querySelectorAll('.language').forEach((button) => button.addEventListener('click', () => setLanguage(button.dataset.lang)));
menuToggle.addEventListener('click', () => { const isOpen = mobileNav.classList.toggle('is-open'); menuToggle.setAttribute('aria-expanded', String(isOpen)); });
mobileNav.querySelectorAll('a').forEach((link) => link.addEventListener('click', () => { mobileNav.classList.remove('is-open'); menuToggle.setAttribute('aria-expanded', 'false'); }));
window.addEventListener('scroll', () => header.classList.toggle('is-scrolled', window.scrollY > 10), { passive: true });

function openModal() { modal.classList.add('is-open'); modal.setAttribute('aria-hidden', 'false'); document.body.classList.add('modal-open'); modal.querySelector('input').focus(); }
function closeModal() { modal.classList.remove('is-open'); modal.setAttribute('aria-hidden', 'true'); document.body.classList.remove('modal-open'); }
document.querySelectorAll('.open-modal').forEach((button) => button.addEventListener('click', openModal));
modal.querySelectorAll('[data-close-modal]').forEach((element) => element.addEventListener('click', closeModal));
document.addEventListener('keydown', (event) => { if (event.key === 'Escape' && modal.classList.contains('is-open')) closeModal(); });

function handleForm(form) { form.addEventListener('submit', (event) => { event.preventDefault(); const status = form.querySelector('.form-status'); status.textContent = document.documentElement.lang === 'uk' ? 'Дякуємо. Ми зателефонуємо вам найближчим часом.' : 'Thank you. We will call you shortly.'; form.reset(); }); }
handleForm(document.querySelector('#lead-form')); handleForm(document.querySelector('#modal-form'));

const observer = new IntersectionObserver((entries) => entries.forEach((entry) => { if (entry.isIntersecting) { entry.target.classList.add('is-visible'); observer.unobserve(entry.target); } }), { threshold: .12 });
document.querySelectorAll('.reveal').forEach((element) => observer.observe(element));
setLanguage(localStorage.getItem('milo-language') || 'ua');
